### ISSUE TITLE
colorbox content misaligned

### ISSUE THREAD

**Issue by rustyper** [lkoehl/typst-boxes#1]
With version 0.4.0 of typst the content of the first example box (colorbox) is misaligned. 

I have "fixed" it by adding an empty line XOR a #v(0pt)  statement between the two boxes inside the outer box in the module file. But I doubt  that this is more than a workaround for some other problem.

**Comment by lkoehl** [comment]
Thanks for pointing it out. It looks rather bizarre for me. I will take a closer look tomorrow.

**Comment by lkoehl** [comment]
I couldn't wait.
The Typst documentation defines a box as 
> An inline-level container that sizes content.

As you said, you could add a new line or add `#v(0pt)` to force a line break. I think changing `box` to `block` would be a better way to solve the problem. However, I will release the fix tomorrow.

**Comment by rustyper** [comment]
Thank you! :-) I'm not that familiar with typst to know that the switch to block is the better solution.
