### ISSUE TITLE
[Feature Request] more colors

### ISSUE THREAD

**Issue by terefang** [lkoehl/typst-boxes#14]
more color definitions:

```
  yellow: (stroke: rgb(238, 238, 0), fill: rgb(255, 255, 192), title: black),
  purple: (stroke: rgb(238, 0, 238), fill: rgb(255, 221, 255), title: white),
  cyan: (stroke: rgb(0, 238, 238), fill: rgb(221, 255, 255), title: black),
  magenta: (stroke: rgb(255, 0, 128), fill: rgb(255, 192, 221), title: white),
  orange: (stroke: rgb(255, 115, 0), fill: rgb(255, 209, 171), title: white),
```

**Comment by lkoehl** [comment]
These colors don't quite fit the already existing colors. I will add some more though.

**Comment by terefang** [comment]
do you have a particular color schema, and strategy how to derive the fill color from the stroke color or vis-versa ?

**Comment by terefang** [comment]
i was looking for a color palette similar to https://lospec.com/palette-list/spectral-16

**Comment by lkoehl** [comment]
There isn't a particular pattern. The colors should be visually pleasing - vibrant but not causing eyestrain like neon colors. Most of the simple color palettes I've seen in documents use colors that don't look good out of the box. I am trying to avoid it with these boxes. 

I can think of using hsl-format and adjusting the hue could potentially be an easy way.

**Comment by terefang** [comment]
looks nice
![image](https://github.com/user-attachments/assets/4a6c7956-c566-4a89-ae32-d1aacc8bf813)

**Comment by terefang** [comment]
is the rounding here intentional ?
![image](https://github.com/user-attachments/assets/0ada8ca8-a868-4698-89e1-6c9ed115b170)

i would like to have it configurable straight.

**Comment by terefang** [comment]
also wrong behaviour here ?
![image](https://github.com/user-attachments/assets/3b2994fe-dcad-4894-8799-5d66ed97b5d4)

**Comment by lkoehl** [comment]
The rounding isn't intentional, but I kinda like it. I added a `colorbox-rounded` version.

The behavior of the slanted version is hard to avoid, since the shape is based on a polygon. I currently don't see an easy fix.
