### ISSUE TITLE
[Feature Request] allow color definition to be read from user-provided external definition file

### ISSUE THREAD

**Issue by terefang** [lkoehl/typst-boxes#17]
referencing https://github.com/lkoehl/typst-boxes/issues/14

would it be possible to load color definitions from an external file (eg. JSON) ?

**Comment by lkoehl** [comment]
It's certainly possible and likely quite straightforward to implement. However, I don't see a strong case for including this functionality directly in the package. Instead, you can define your colors in an external JSON or another format, load them into your Typst template, and pass them as `box-colors` when using the package.
