### ISSUE TITLE
Submit typst-boxes to the package repository of the typst project

### ISSUE THREAD

**Issue by rustyper** [lkoehl/typst-boxes#2]
It would be nice to have this package in the "official" package repository of the typst project.
@lkoehl do you have any interest to submit it there? 
Otherwise, I can also try to bring it in there, if this is ok for you...

**Comment by lkoehl** [comment]
I will have a look on how to submit a package. Im guessing, there will be some naming problems, since typst-boxes is too generic. 
It might make sense to merge repos with [showybox](https://github.com/typst/packages/tree/main/packages/preview/showybox-0.2.0).
I am also not quite sure where to go with this repo. I don't quite think having a lot of customizability is the way to go. Providing a couple of good looking boxes with a bit of customization sounds better to me. I never liked how the easy examples in tcolorbox looked.And it seems like showybox is working reproducing some functionality from tcolorbox.

What do you think about it @rustyper

**Comment by lkoehl** [comment]
After reviewing the naming guidelines, it is evident that a project renaming will be necessary.

> Naming: Package names should not be merely descriptive to create level grounds for everybody (e.g. slides is forbidden, but sliding or slitastic would be ok). Names should not include the word "typst" (as it is redundant). If they contain multiple words, names should use kebab-case. Look at existing packages and PRs to get a feel for what's allowed and what's not.

**Comment by rustyper** [comment]
In my opinion giving users a couple of alternative packages to choose from is a good thing. So I would not merge with showybox.

And yes, according to the naming policy typst-boxes is most probably not an acceptable name. I not a really creative person, but maybe something like notesticker is approriate? The idea for this name stems from the fact, that I use this boxes in my teaching material and exams (Klassenarbeiten) to highlight hints for the pupils in the form of stickers.

**Comment by lkoehl** [comment]
Currently thinking about "colorboxes" or "colorful-boxes", since its not just the sticky note. We are having the same use case of this library. You can also check out [schule-typst](https://github.com/jneug/schule-typst).

**Comment by rustyper** [comment]
You are right, the my suggestion only highlights one boxtyp, so your names are definitely a better option. Thanks for the hint to [schule-typst](https://github.com/jneug/schule-typst). :-)

**Comment by jneug** [comment]
Nice to see some teaching colleagues experimenting with Typst. :-) 

I'd definitely would like to see the package ecosystem grow and having alternatives is always a good thing. I just contributed to `showybox` but certainly see the benefit of having a package with a limited set of options.

The name `colorboxes` is very close to `tcolorbox`. Maybe that will get some people confused? Perhaps something along the line of `colorframes`?

**Comment by lkoehl** [comment]
I decided to go with the name `colorful-boxes` because thats what this package aims to provide. You can track the pull request [here](https://github.com/typst/packages/pull/53).

**Comment by lkoehl** [comment]
Done
