### ISSUE TITLE
Remove `codetastic` dependency

### ISSUE THREAD

**Issue by sitandr** [lkoehl/typst-boxes#5]
Codetastic may be a good library, but is quite heavy, with lots of inefficient Typst code.

I think users can figure out they can put qr-codes inside colorful-boxes themselves, the library should not add just another dependency for nothing, without even documenting it.

**Comment by lkoehl** [comment]
I agree. The dependency will be removed in future versions.

**Comment by lkoehl** [comment]
See #7
